language: node_js #设置语言
node_js: stable # nodejs版本
branches:
  only:
    - master #只监测master分支
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
before_install:
  # - git config --global user.name "zlaccount"  # github用户名
  # - git config --global user.email "1473002554@qq.com"  # 邮箱
  - npm install 
install:
  - npm i
before_script:
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  # - git config --global user.name "${U_NAME}"
  # - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update tools"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" master:master
env:
 global:
   - GH_REF: ${GH_REF} #设置GH_REF,换成自己用户名和仓库名
